const messages = {
  success: {
    otpSend: "Otp has been sent to your Phone",
    otpSendmobile: "Otp has been sent to your mobile",
    otpVerify: "Otp verified successfully",
    otpEmailSend: "Otp has been sent to your email address",
    forgetPassword: "Email has been sent with password reset link",
    ResetPassword: "Password has been reset",
    logout: "Logout Successfully",
    changePassword: "Password has been changed successfully.",
    planBuy: "Plan buy successfully.",
    defaultMessage: "Saved successfully",
    signup: "User Registered Successfully",
    BusinessSignup: "Business Registered Successfully",
    login: "User login successfully",
    logout: "User logout successfully",
    getMyProfile: "Profile retrieved successfully",
    updateProfile: "Profile updated successfully",
    updateRole: "Role updated successfully",
    setpProfile: "Profile setup successfully",
    updateProfileImage: "Profile Image uploaded successfully",
    createUser: "User created successfully",
    created: "created successfully",
    updateUser: "User update successfully",
    userDeleted: "User Deleted successfully",
    fetchsucess: "Successfully Get",
    updatesucess: "Successfully Updated",
    deletesucess: "Successfully Deleted",
    ServiceCreateSucess: "Service created Successfully",
    RequestCreateSucess: "Request Submited Successfully",
  },
  error: {
    default: "Oops! something went wrong",
    optExpired: "Otp has been expired",
    inavalidOtp: "Invalid Otp.",
    alreadyVerifyOtp: "Otp already verified.",
    inavalidEmail: "Invalid email id.",
    invalidPassword:'Invalid Password',
    emailAlreadyExist: "This email is already registered with us",
    blockUser: "Your account has been blocked. Please contact admin",
    approveUser: "Your account is not approve. Please contact admin",
    phoneNumberAlreadyExist: "This Phone number is already registered with us",
    image:"Please choose image",
    inavalidUser: "Invalid user.",
    noFoundPolicy: "Policy Not Found",
    noFoundHelp: "Help Not Found",
    nameUnique: "Business Name already exist ,please choose different name",
  },
  status: {
    validation: "Unprocessable Entity",
    authorization: "Unauthorized",
    internalServerError: "Internal Server Error",
    badRequest: "Bad Request",
  },
};

module.exports = messages;
